### ISSUE TITLE
"avoid `.get()` to get a single element" guideline

### ISSUE THREAD

**Issue by Ex-iT** [voorhoede/jquery-style-guide#19]
To reduce the overhead of using `.get( index )` you can use the `[ index ]` to get a single element from a matched jQuery collection.

A drawback would be that you can't use a negative index to count from the end of the matched set.

``` javascript
<!-- avoid: -->
$listItem = $list.find('li').get(2);

<!-- recommended: reduce overhead -->
$listItem = $list.find('li')[2];
```

Should we make this a guideline?

**Comment by reinoute** [comment]
According to [this](http://stackoverflow.com/questions/4975716/jquery-array-zero-vs-function-get-zero-0-vs-get0) there's no difference, since it's both an array.

But we could recommend when you should work with Jquery objects (`$list.find('li').eq(2)`) or with raw DOM elements (`$list.find('li').get(2)`).

**Comment by jpsc** [comment]
There is no difference when you are working to get a specific element.
But if you want to use something like `map()` / `reduce()` to iterate from your selection, using get() returns you a "clean" array from the jQuery object.

This seams to me like a tip and not a guideline.

**Comment by jpsc** [comment]
Going to close since it does not look like a guideline.
